"""
MÓDULO: etl.loader

RESPONSABILIDAD:
- Insertar datos en la base de datos.

FUNCIONES:

1. load_clientes(df, engine)
   - Inserta en tabla 'clientes'
   - if_exists = 'append'

2. load_tarjetas(df, engine)
   - Inserta en tabla 'tarjetas'

3. save_output_csv(df, output_path, filename)
   - Guarda CSV transformado

VARIABLES:
- TABLE_CLIENTES
- TABLE_TARJETAS

INTERACCIÓN:
- pipeline.py
- db.connection.py

CONSIDERACIONES:
- Evitar duplicados (posible mejora futura)
- Manejo de errores de inserción
"""
import os

import pandas as pd
from sqlalchemy import inspect
from sqlalchemy import text


def _get_table_columns(engine, table_name: str) -> list:
    inspector = inspect(engine)
    return [column["name"] for column in inspector.get_columns(table_name)]


def _get_primary_key_columns(engine, table_name: str) -> list:
    inspector = inspect(engine)
    return inspector.get_pk_constraint(table_name).get("constrained_columns", [])


def _filter_existing_rows(df: pd.DataFrame, engine, table_name: str, key_column: str) -> pd.DataFrame:
    if key_column not in df.columns or df.empty:
        return df

    keys = [
        value for value in df[key_column].dropna().astype(str).unique().tolist()
        if value != ""
    ]
    if not keys:
        return df

    query = text(f"SELECT {key_column} FROM {table_name} WHERE {key_column} = ANY(:keys)")
    with engine.connect() as connection:
        existing = {
            str(row[0])
            for row in connection.execute(query, {"keys": keys})
        }

    if not existing:
        return df

    filtered = df[~df[key_column].astype(str).isin(existing)].copy()
    return filtered


def _drop_autogenerated_primary_keys(df: pd.DataFrame, primary_keys: list) -> pd.DataFrame:
    trimmed = df.copy()
    for key in primary_keys:
        if key in trimmed.columns and trimmed[key].isna().all():
            trimmed = trimmed.drop(columns=[key])
    return trimmed


def _adapt_clientes_dataframe(df: pd.DataFrame, table_columns: list) -> pd.DataFrame:
    adapted = df.copy()

    # Compatibilidad con el esquema legado que exigía cod_cliente y apellidos.
    if "cod_cliente" in table_columns and "cod_cliente" not in adapted.columns:
        adapted["cod_cliente"] = adapted["dni_hash"]
    if "apellido1" in table_columns and "apellido1" not in adapted.columns:
        adapted["apellido1"] = None
    if "apellido2" in table_columns and "apellido2" not in adapted.columns:
        adapted["apellido2"] = None

    # Rellenar posibles columnas de la tabla que no vengan en el DataFrame.
    for column in table_columns:
        if column not in adapted.columns:
            adapted[column] = None

    return adapted[table_columns]


def _adapt_tarjetas_dataframe(df: pd.DataFrame, table_columns: list) -> pd.DataFrame:
    adapted = df.copy()

    # Compatibilidad con el esquema legado.
    if "cod_cliente" in table_columns and "cod_cliente" not in adapted.columns and "id_cliente" in adapted.columns:
        adapted["cod_cliente"] = adapted["id_cliente"]
    if "fecha_exp" in table_columns and "fecha_exp" not in adapted.columns and "fecha_caducidad" in adapted.columns:
        adapted["fecha_exp"] = adapted["fecha_caducidad"]

    for column in table_columns:
        if column not in adapted.columns:
            adapted[column] = None

    return adapted[table_columns]

def load_clientes(df: pd.DataFrame, engine) -> None:
    table_columns = _get_table_columns(engine, "clientes")
    adapted = _adapt_clientes_dataframe(df, table_columns)
    primary_keys = _get_primary_key_columns(engine, "clientes")
    adapted = _drop_autogenerated_primary_keys(adapted, primary_keys)
    if len(primary_keys) == 1:
        adapted = _filter_existing_rows(adapted, engine, "clientes", primary_keys[0])
    if adapted.empty:
        return
    adapted.to_sql("clientes", engine, if_exists="append", index=False)
    
def load_tarjetas(df: pd.DataFrame, engine) -> None:
    table_columns = _get_table_columns(engine, "tarjetas")
    adapted = _adapt_tarjetas_dataframe(df, table_columns)
    primary_keys = _get_primary_key_columns(engine, "tarjetas")
    adapted = _drop_autogenerated_primary_keys(adapted, primary_keys)
    if len(primary_keys) == 1 and primary_keys[0] != "id":
        adapted = _filter_existing_rows(adapted, engine, "tarjetas", primary_keys[0])
    if adapted.empty:
        return
    adapted.to_sql("tarjetas", engine, if_exists="append", index=False)
    
def save_output_csv(df: pd.DataFrame, output_path: str, filename: str) -> None:
    os.makedirs(output_path, exist_ok=True)
    df.to_csv(os.path.join(output_path, filename), sep=";", index=False)
